// Corporate Cards Mock Data
// Comprehensive demonstration data for the corporate cards management system

import {
  CorporateCard,
  Transaction,
  CardRequest,
  CardAnalytics,
  FraudAlert,
  CardSettings,
  Subscription,
  CardStatus,
  CardType,
  TransactionStatus,
  TransactionType,
  TransactionCategory,
  CardRequestStatus,
  FraudAlertLevel,
  SpendingLimitType,
} from '@/types/corporate-cards'

// ==================== Corporate Cards ====================

export const mockCorporateCards: CorporateCard[] = [
  {
    id: 'card_001',
    cardNumber: '4532',
    cardholderName: 'Sarah Johnson',
    cardholderEmail: 'sarah.johnson@wiremi.com',
    employeeId: 'emp_001',
    department: 'Marketing',
    type: 'PHYSICAL',
    status: 'ACTIVE',
    lastFourDigits: '4532',
    expiryMonth: 8,
    expiryYear: 2027,
    spendingLimits: [
      {
        id: 'limit_001',
        type: 'DAILY',
        amount: 1000,
        spent: 450,
        remaining: 550,
        resetDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'limit_002',
        type: 'MONTHLY',
        amount: 15000,
        spent: 8750,
        remaining: 6250,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
    ],
    availableBalance: 6250,
    restrictions: {
      allowedCategories: ['ADVERTISING', 'SOFTWARE', 'OFFICE_SUPPLIES'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: false,
    },
    nickname: 'Marketing Campaign Card',
    assignedFor: 'Digital advertising and marketing tools',
    totalSpent: 8750,
    transactionCount: 47,
    lastUsed: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-03-15T00:00:00Z',
    activatedDate: '2025-03-16T00:00:00Z',
    expiresAt: '2027-08-31T00:00:00Z',
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'card_002',
    cardNumber: '5412',
    cardholderName: 'Michael Chen',
    cardholderEmail: 'michael.chen@wiremi.com',
    employeeId: 'emp_002',
    department: 'Engineering',
    type: 'VIRTUAL',
    status: 'ACTIVE',
    lastFourDigits: '5412',
    expiryMonth: 12,
    expiryYear: 2026,
    cvv: '789',
    spendingLimits: [
      {
        id: 'limit_003',
        type: 'DAILY',
        amount: 500,
        spent: 120,
        remaining: 380,
        resetDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'limit_004',
        type: 'MONTHLY',
        amount: 5000,
        spent: 3200,
        remaining: 1800,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
    ],
    availableBalance: 1800,
    restrictions: {
      allowedCategories: ['SOFTWARE', 'SUBSCRIPTIONS', 'HARDWARE'],
      allowOnlineTransactions: true,
      allowInternational: false,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: false,
    },
    nickname: 'Dev Tools Card',
    assignedFor: 'Software subscriptions and development tools',
    totalSpent: 3200,
    transactionCount: 28,
    lastUsed: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-04-01T00:00:00Z',
    activatedDate: '2025-04-01T00:00:00Z',
    expiresAt: '2026-12-31T00:00:00Z',
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'card_003',
    cardNumber: '6011',
    cardholderName: 'Emily Rodriguez',
    cardholderEmail: 'emily.rodriguez@wiremi.com',
    employeeId: 'emp_003',
    department: 'Sales',
    type: 'PHYSICAL',
    status: 'ACTIVE',
    lastFourDigits: '6011',
    expiryMonth: 6,
    expiryYear: 2028,
    spendingLimits: [
      {
        id: 'limit_005',
        type: 'DAILY',
        amount: 2000,
        spent: 1850,
        remaining: 150,
        resetDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'limit_006',
        type: 'MONTHLY',
        amount: 25000,
        spent: 18900,
        remaining: 6100,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
      {
        id: 'limit_007',
        type: 'PER_TRANSACTION',
        amount: 5000,
        spent: 0,
        remaining: 5000,
      },
    ],
    availableBalance: 6100,
    restrictions: {
      allowedCategories: ['TRAVEL', 'MEALS', 'ENTERTAINMENT', 'PROFESSIONAL_SERVICES'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: true,
      requireReceipt: true,
      requireApproval: true,
      approvalThreshold: 2500,
    },
    nickname: 'Sales Travel Card',
    assignedFor: 'Client meetings and business travel',
    notes: 'Requires approval for transactions over $2,500',
    totalSpent: 18900,
    transactionCount: 62,
    lastUsed: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-01-10T00:00:00Z',
    activatedDate: '2025-01-10T00:00:00Z',
    expiresAt: '2028-06-30T00:00:00Z',
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'card_004',
    cardNumber: '3782',
    cardholderName: 'David Park',
    cardholderEmail: 'david.park@wiremi.com',
    employeeId: 'emp_004',
    department: 'Operations',
    type: 'VIRTUAL',
    status: 'FROZEN',
    lastFourDigits: '3782',
    expiryMonth: 3,
    expiryYear: 2027,
    cvv: '456',
    spendingLimits: [
      {
        id: 'limit_008',
        type: 'MONTHLY',
        amount: 8000,
        spent: 4200,
        remaining: 3800,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
    ],
    availableBalance: 3800,
    restrictions: {
      allowedCategories: ['UTILITIES', 'OFFICE_SUPPLIES', 'RENT'],
      allowOnlineTransactions: true,
      allowInternational: false,
      allowATMWithdrawal: false,
      requireReceipt: false,
      requireApproval: false,
    },
    nickname: 'Office Operations',
    assignedFor: 'Office utilities and supplies',
    notes: 'Temporarily frozen for review',
    totalSpent: 4200,
    transactionCount: 19,
    lastUsed: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-05-20T00:00:00Z',
    activatedDate: '2025-05-20T00:00:00Z',
    expiresAt: '2027-03-31T00:00:00Z',
    createdAt: '2025-05-20T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'card_005',
    cardNumber: '5555',
    cardholderName: 'Lisa Thompson',
    cardholderEmail: 'lisa.thompson@wiremi.com',
    employeeId: 'emp_005',
    department: 'Design',
    type: 'SUBSCRIPTION',
    status: 'ACTIVE',
    lastFourDigits: '5555',
    expiryMonth: 9,
    expiryYear: 2027,
    cvv: '123',
    spendingLimits: [
      {
        id: 'limit_009',
        type: 'MONTHLY',
        amount: 3000,
        spent: 2100,
        remaining: 900,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
    ],
    availableBalance: 900,
    restrictions: {
      allowedCategories: ['SUBSCRIPTIONS', 'SOFTWARE'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: false,
      requireReceipt: false,
      requireApproval: false,
    },
    nickname: 'Design Subscriptions',
    assignedFor: 'Adobe Creative Cloud, Figma, and other design tools',
    totalSpent: 2100,
    transactionCount: 8,
    lastUsed: new Date(Date.now() - 720 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-02-01T00:00:00Z',
    activatedDate: '2025-02-01T00:00:00Z',
    expiresAt: '2027-09-30T00:00:00Z',
    createdAt: '2025-02-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'card_006',
    cardNumber: '4916',
    cardholderName: 'James Wilson',
    cardholderEmail: 'james.wilson@wiremi.com',
    employeeId: 'emp_006',
    department: 'Finance',
    type: 'PHYSICAL',
    status: 'ACTIVE',
    lastFourDigits: '4916',
    expiryMonth: 11,
    expiryYear: 2026,
    spendingLimits: [
      {
        id: 'limit_010',
        type: 'DAILY',
        amount: 1500,
        spent: 650,
        remaining: 850,
        resetDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'limit_011',
        type: 'MONTHLY',
        amount: 20000,
        spent: 12400,
        remaining: 7600,
        resetDate: new Date(2026, 1, 1).toISOString(),
      },
    ],
    availableBalance: 7600,
    restrictions: {
      allowedCategories: ['PROFESSIONAL_SERVICES', 'INSURANCE', 'SOFTWARE'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: true,
      approvalThreshold: 5000,
    },
    nickname: 'Finance Operations',
    assignedFor: 'Financial services and professional fees',
    totalSpent: 12400,
    transactionCount: 34,
    lastUsed: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    issuedDate: '2025-06-01T00:00:00Z',
    activatedDate: '2025-06-02T00:00:00Z',
    expiresAt: '2026-11-30T00:00:00Z',
    createdAt: '2025-06-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
]

// ==================== Transactions ====================

export const mockTransactions: Transaction[] = [
  {
    id: 'txn_001',
    cardId: 'card_001',
    cardLastFour: '4532',
    cardholderName: 'Sarah Johnson',
    employeeId: 'emp_001',
    type: 'PURCHASE',
    status: 'COMPLETED',
    category: 'ADVERTISING',
    merchantName: 'Google Ads',
    merchantCategory: 'advertising',
    merchantCountry: 'United States',
    amount: 2500.00,
    currency: 'USD',
    description: 'Q1 Marketing Campaign',
    transactionDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    receiptUrl: 'https://example.com/receipts/txn_001.pdf',
    receiptUploaded: true,
    reimbursable: false,
    notes: 'Q1 digital advertising campaign spend',
    tags: ['marketing', 'digital', 'q1-2026'],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_002',
    cardId: 'card_002',
    cardLastFour: '5412',
    cardholderName: 'Michael Chen',
    employeeId: 'emp_002',
    type: 'SUBSCRIPTION',
    status: 'COMPLETED',
    category: 'SOFTWARE',
    merchantName: 'GitHub',
    merchantCategory: 'saas',
    merchantCountry: 'United States',
    amount: 99.00,
    currency: 'USD',
    description: 'GitHub Enterprise Monthly Subscription',
    transactionDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    tags: ['subscription', 'development', 'tools'],
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_003',
    cardId: 'card_003',
    cardLastFour: '6011',
    cardholderName: 'Emily Rodriguez',
    employeeId: 'emp_003',
    type: 'PURCHASE',
    status: 'COMPLETED',
    category: 'TRAVEL',
    merchantName: 'United Airlines',
    merchantCategory: 'airline',
    merchantCountry: 'United States',
    amount: 1850.00,
    currency: 'USD',
    description: 'Flight to NYC for client meeting',
    transactionDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    receiptUrl: 'https://example.com/receipts/txn_003.pdf',
    receiptUploaded: true,
    reimbursable: false,
    notes: 'Meeting with ABC Corp executives',
    tags: ['travel', 'sales', 'nyc'],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_004',
    cardId: 'card_001',
    cardLastFour: '4532',
    cardholderName: 'Sarah Johnson',
    employeeId: 'emp_001',
    type: 'PURCHASE',
    status: 'PENDING',
    category: 'SOFTWARE',
    merchantName: 'Adobe',
    merchantCategory: 'software',
    merchantCountry: 'United States',
    amount: 599.00,
    currency: 'USD',
    description: 'Adobe Creative Cloud Team License',
    transactionDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    tags: ['software', 'design', 'license'],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_005',
    cardId: 'card_003',
    cardLastFour: '6011',
    cardholderName: 'Emily Rodriguez',
    employeeId: 'emp_003',
    type: 'PURCHASE',
    status: 'COMPLETED',
    category: 'MEALS',
    merchantName: 'The Capital Grille',
    merchantCategory: 'restaurant',
    merchantCountry: 'United States',
    amount: 385.50,
    currency: 'USD',
    description: 'Client dinner',
    transactionDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    receiptUrl: 'https://example.com/receipts/txn_005.pdf',
    receiptUploaded: true,
    reimbursable: false,
    notes: 'Dinner with prospective client',
    tags: ['meals', 'entertainment', 'client'],
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_006',
    cardId: 'card_004',
    cardLastFour: '3782',
    cardholderName: 'David Park',
    employeeId: 'emp_004',
    type: 'PURCHASE',
    status: 'DECLINED',
    category: 'OFFICE_SUPPLIES',
    merchantName: 'Staples',
    merchantCategory: 'office',
    merchantCountry: 'United States',
    amount: 450.00,
    currency: 'USD',
    description: 'Office supplies order',
    transactionDate: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    notes: 'Declined - card was frozen',
    tags: ['office', 'supplies'],
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_007',
    cardId: 'card_006',
    cardLastFour: '4916',
    cardholderName: 'James Wilson',
    employeeId: 'emp_006',
    type: 'PURCHASE',
    status: 'COMPLETED',
    category: 'PROFESSIONAL_SERVICES',
    merchantName: 'Legal Services LLC',
    merchantCategory: 'consulting',
    merchantCountry: 'United States',
    amount: 4500.00,
    currency: 'USD',
    description: 'Legal consultation services',
    transactionDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    receiptUrl: 'https://example.com/receipts/txn_007.pdf',
    receiptUploaded: true,
    reimbursable: false,
    notes: 'Contract review and legal advice',
    tags: ['legal', 'professional-services'],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_008',
    cardId: 'card_002',
    cardLastFour: '5412',
    cardholderName: 'Michael Chen',
    employeeId: 'emp_002',
    type: 'PURCHASE',
    status: 'DISPUTED',
    category: 'HARDWARE',
    merchantName: 'Unknown Merchant',
    merchantCategory: 'hardware',
    merchantCountry: 'China',
    amount: 1200.00,
    currency: 'USD',
    localAmount: 8640.00,
    localCurrency: 'CNY',
    exchangeRate: 7.2,
    description: 'Suspicious hardware purchase',
    transactionDate: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 71 * 60 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    notes: 'Transaction disputed - not authorized',
    fraudScore: 85,
    fraudFlags: ['unusual_location', 'high_amount', 'unknown_merchant'],
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_009',
    cardId: 'card_005',
    cardLastFour: '5555',
    cardholderName: 'Lisa Thompson',
    employeeId: 'emp_005',
    type: 'SUBSCRIPTION',
    status: 'COMPLETED',
    category: 'SUBSCRIPTIONS',
    merchantName: 'Figma',
    merchantCategory: 'saas',
    merchantCountry: 'United States',
    amount: 144.00,
    currency: 'USD',
    description: 'Figma Professional Annual Subscription',
    transactionDate: new Date(Date.now() - 720 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 719 * 60 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    tags: ['subscription', 'design', 'tools'],
    createdAt: new Date(Date.now() - 720 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'txn_010',
    cardId: 'card_001',
    cardLastFour: '4532',
    cardholderName: 'Sarah Johnson',
    employeeId: 'emp_001',
    type: 'REFUND',
    status: 'COMPLETED',
    category: 'ADVERTISING',
    merchantName: 'Meta Business',
    merchantCategory: 'advertising',
    merchantCountry: 'United States',
    amount: -350.00,
    currency: 'USD',
    description: 'Refund for cancelled ad campaign',
    transactionDate: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    postDate: new Date(Date.now() - 119 * 60 * 60 * 1000).toISOString(),
    receiptUploaded: false,
    reimbursable: false,
    notes: 'Campaign cancelled due to budget reallocation',
    tags: ['refund', 'advertising'],
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

// ==================== Card Requests ====================

export const mockCardRequests: CardRequest[] = [
  {
    id: 'req_001',
    requesterId: 'emp_007',
    requesterName: 'Alex Martinez',
    requesterEmail: 'alex.martinez@wiremi.com',
    department: 'Product',
    cardType: 'VIRTUAL',
    purpose: 'Product research and competitor analysis',
    justification: 'Need dedicated card for purchasing competitor products and conducting market research',
    requestedLimits: [
      { type: 'MONTHLY', amount: 3000 },
    ],
    requestedRestrictions: {
      allowedCategories: ['SOFTWARE', 'SUBSCRIPTIONS', 'OTHER'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: false,
    },
    status: 'PENDING',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req_002',
    requesterId: 'emp_008',
    requesterName: 'Rachel Kim',
    requesterEmail: 'rachel.kim@wiremi.com',
    department: 'HR',
    cardType: 'PHYSICAL',
    purpose: 'Employee events and team building',
    justification: 'Need card for organizing company events, team lunches, and employee engagement activities',
    requestedLimits: [
      { type: 'MONTHLY', amount: 5000 },
      { type: 'PER_TRANSACTION', amount: 2000 },
    ],
    requestedRestrictions: {
      allowedCategories: ['MEALS', 'ENTERTAINMENT', 'OFFICE_SUPPLIES'],
      allowOnlineTransactions: true,
      allowInternational: false,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: true,
      approvalThreshold: 1000,
    },
    status: 'APPROVED',
    approvedBy: 'admin_001',
    approvedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req_003',
    requesterId: 'emp_009',
    requesterName: 'Tom Anderson',
    requesterEmail: 'tom.anderson@wiremi.com',
    department: 'Sales',
    cardType: 'PHYSICAL',
    purpose: 'International sales travel',
    justification: 'Expanding to EMEA region, need card for frequent international travel',
    requestedLimits: [
      { type: 'MONTHLY', amount: 30000 },
      { type: 'DAILY', amount: 3000 },
    ],
    requestedRestrictions: {
      allowedCategories: ['TRAVEL', 'MEALS', 'ENTERTAINMENT', 'PROFESSIONAL_SERVICES'],
      allowOnlineTransactions: true,
      allowInternational: true,
      allowATMWithdrawal: true,
      requireReceipt: true,
      requireApproval: true,
      approvalThreshold: 5000,
    },
    status: 'ISSUED',
    approvedBy: 'admin_001',
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    issuedCardId: 'card_007',
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'req_004',
    requesterId: 'emp_010',
    requesterName: 'Nina Patel',
    requesterEmail: 'nina.patel@wiremi.com',
    department: 'Marketing',
    cardType: 'VIRTUAL_SINGLE_USE',
    purpose: 'One-time vendor payment',
    justification: 'Need to pay new vendor for marketing materials, prefer single-use card for security',
    requestedLimits: [
      { type: 'PER_TRANSACTION', amount: 5000 },
    ],
    requestedRestrictions: {
      allowOnlineTransactions: true,
      allowInternational: false,
      allowATMWithdrawal: false,
      requireReceipt: true,
      requireApproval: false,
    },
    status: 'REJECTED',
    rejectedReason: 'Single-use cards require finance approval. Please request standard virtual card and submit vendor through procurement.',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// ==================== Fraud Alerts ====================

export const mockFraudAlerts: FraudAlert[] = [
  {
    id: 'fraud_001',
    cardId: 'card_002',
    transactionId: 'txn_008',
    level: 'HIGH',
    reason: 'Suspicious international transaction',
    description: 'Transaction from unusual location (China) with unknown merchant',
    flaggedPatterns: ['unusual_location', 'high_amount', 'unknown_merchant', 'international_blocked'],
    riskScore: 85,
    confidence: 0.92,
    reviewed: true,
    reviewedBy: 'admin_001',
    reviewedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    resolution: 'CONFIRMED_FRAUD',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'fraud_002',
    cardId: 'card_003',
    transactionId: 'txn_011',
    level: 'MEDIUM',
    reason: 'Multiple transactions in short time',
    description: 'Card used for 5 transactions within 15 minutes',
    flaggedPatterns: ['rapid_transactions', 'velocity_check'],
    riskScore: 62,
    confidence: 0.78,
    reviewed: true,
    reviewedBy: 'admin_001',
    reviewedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    resolution: 'FALSE_POSITIVE',
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'fraud_003',
    cardId: 'card_001',
    transactionId: 'txn_012',
    level: 'LOW',
    reason: 'Unusual merchant category',
    description: 'Transaction in category not typically used by this card',
    flaggedPatterns: ['unusual_category'],
    riskScore: 35,
    confidence: 0.55,
    reviewed: false,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'fraud_004',
    cardId: 'card_006',
    transactionId: 'txn_013',
    level: 'CRITICAL',
    reason: 'Card details potentially compromised',
    description: 'Multiple failed authorization attempts detected',
    flaggedPatterns: ['multiple_declines', 'cvv_mismatch', 'potential_breach'],
    riskScore: 95,
    confidence: 0.96,
    reviewed: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
]

// ==================== Subscriptions ====================

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub_001',
    cardId: 'card_002',
    merchantName: 'GitHub',
    description: 'GitHub Enterprise',
    category: 'SOFTWARE',
    amount: 99.00,
    currency: 'USD',
    billingFrequency: 'MONTHLY',
    nextBillingDate: new Date(2026, 1, 15).toISOString(),
    status: 'ACTIVE',
    firstCharged: '2025-04-15T00:00:00Z',
    lastCharged: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    totalPaid: 891.00,
    paymentCount: 9,
    createdAt: '2025-04-15T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_002',
    cardId: 'card_005',
    merchantName: 'Adobe',
    description: 'Adobe Creative Cloud',
    category: 'SOFTWARE',
    amount: 599.88,
    currency: 'USD',
    billingFrequency: 'ANNUAL',
    nextBillingDate: new Date(2027, 0, 1).toISOString(),
    status: 'ACTIVE',
    firstCharged: '2025-01-01T00:00:00Z',
    lastCharged: '2026-01-01T00:00:00Z',
    totalPaid: 1199.76,
    paymentCount: 2,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_003',
    cardId: 'card_005',
    merchantName: 'Figma',
    description: 'Figma Professional',
    category: 'SUBSCRIPTIONS',
    amount: 144.00,
    currency: 'USD',
    billingFrequency: 'ANNUAL',
    nextBillingDate: new Date(2027, 0, 1).toISOString(),
    status: 'ACTIVE',
    firstCharged: '2025-01-01T00:00:00Z',
    lastCharged: new Date(Date.now() - 720 * 60 * 60 * 1000).toISOString(),
    totalPaid: 288.00,
    paymentCount: 2,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_004',
    cardId: 'card_002',
    merchantName: 'AWS',
    description: 'Amazon Web Services',
    category: 'SOFTWARE',
    amount: 450.00,
    currency: 'USD',
    billingFrequency: 'MONTHLY',
    nextBillingDate: new Date(2026, 1, 1).toISOString(),
    status: 'ACTIVE',
    firstCharged: '2024-06-01T00:00:00Z',
    lastCharged: '2026-01-01T00:00:00Z',
    totalPaid: 3150.00,
    paymentCount: 7,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sub_005',
    cardId: 'card_001',
    merchantName: 'Slack',
    description: 'Slack Business+',
    category: 'SOFTWARE',
    amount: 12.50,
    currency: 'USD',
    billingFrequency: 'MONTHLY',
    nextBillingDate: new Date(2026, 1, 1).toISOString(),
    status: 'CANCELLED',
    firstCharged: '2025-01-01T00:00:00Z',
    lastCharged: '2025-12-01T00:00:00Z',
    totalPaid: 150.00,
    paymentCount: 12,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-12-15T00:00:00Z',
  },
]

// ==================== Card Analytics ====================

export const mockCardAnalytics: CardAnalytics = {
  totalCards: 6,
  activeCards: 5,
  frozenCards: 1,
  totalSpend: 49550.00,
  cardsByStatus: {
    ACTIVE: 5,
    INACTIVE: 0,
    FROZEN: 1,
    SUSPENDED: 0,
    EXPIRED: 0,
    CANCELLED: 0,
  },
  spendingThisMonth: 15750.00,
  spendingLastMonth: 18200.00,
  spendingThisYear: 49550.00,
  averageTransactionValue: 425.50,
  spendingByCategory: {
    ADVERTISING: 12500.00,
    SOFTWARE: 8950.00,
    OFFICE_SUPPLIES: 3200.00,
    TRAVEL: 9850.00,
    MEALS: 4100.00,
    ENTERTAINMENT: 1800.00,
    UTILITIES: 2400.00,
    SUBSCRIPTIONS: 2100.00,
    HARDWARE: 1200.00,
    PROFESSIONAL_SERVICES: 4500.00,
    RENT: 0,
    INSURANCE: 0,
    OTHER: 950.00,
  },
  spendingByDepartment: [
    { department: 'Marketing', totalSpend: 21350.00, cardCount: 2 },
    { department: 'Sales', totalSpend: 18900.00, cardCount: 1 },
    { department: 'Finance', totalSpend: 12400.00, cardCount: 1 },
    { department: 'Engineering', totalSpend: 8750.00, cardCount: 1 },
    { department: 'Operations', totalSpend: 4200.00, cardCount: 1 },
    { department: 'Design', totalSpend: 2100.00, cardCount: 1 },
  ],
  spendingByMonth: [
    { month: '2025-07', totalSpend: 8200.00, transactionCount: 42 },
    { month: '2025-08', totalSpend: 9450.00, transactionCount: 51 },
    { month: '2025-09', totalSpend: 7800.00, transactionCount: 38 },
    { month: '2025-10', totalSpend: 10150.00, transactionCount: 56 },
    { month: '2025-11', totalSpend: 11950.00, transactionCount: 63 },
    { month: '2025-12', totalSpend: 18200.00, transactionCount: 78 },
    { month: '2026-01', totalSpend: 15750.00, transactionCount: 68 },
  ],
  topSpenders: [
    { cardId: 'card_001', cardholderName: 'Sarah Johnson', totalSpent: 12500.00, transactionCount: 47 },
    { cardId: 'card_003', cardholderName: 'Emily Rodriguez', totalSpent: 18900.00, transactionCount: 62 },
    { cardId: 'card_006', cardholderName: 'James Wilson', totalSpent: 12400.00, transactionCount: 34 },
    { cardId: 'card_002', cardholderName: 'Michael Chen', totalSpent: 8750.00, transactionCount: 28 },
  ],
  topMerchants: [
    { merchantName: 'Google Ads', totalSpent: 8500.00, transactionCount: 12 },
    { merchantName: 'United Airlines', totalSpent: 6200.00, transactionCount: 8 },
    { merchantName: 'AWS', totalSpent: 3150.00, transactionCount: 7 },
    { merchantName: 'Adobe', totalSpent: 2799.64, transactionCount: 5 },
    { merchantName: 'Legal Services LLC', totalSpent: 4500.00, transactionCount: 3 },
  ],
  fraudAlerts: 4,
  suspiciousTransactions: 2,
}

// ==================== Card Settings ====================

export const mockCardSettings: CardSettings = {
  companyName: 'Wiremi Inc.',
  companyId: 'comp_001',
  defaultDailyLimit: 1000,
  defaultMonthlyLimit: 10000,
  defaultTransactionLimit: 2500,
  defaultRestrictions: {
    allowOnlineTransactions: true,
    allowInternational: false,
    allowATMWithdrawal: false,
    requireReceipt: true,
    requireApproval: false,
  },
  requireApprovalForVirtual: false,
  requireApprovalForPhysical: true,
  autoApprovalLimit: 5000,
  notifyOnTransaction: true,
  notifyOnDecline: true,
  notifyOnFraud: true,
  notificationChannels: ['EMAIL', 'PUSH'],
  requireReceiptForAmount: 100,
  receiptUploadDeadlineDays: 7,
  accountingIntegration: 'QUICKBOOKS',
}

// ==================== Helper Functions ====================

export function getCardById(cardId: string): CorporateCard | undefined {
  return mockCorporateCards.find(card => card.id === cardId)
}

export function getTransactionsByCardId(cardId: string): Transaction[] {
  return mockTransactions.filter(txn => txn.cardId === cardId)
}

export function getCardRequestsByStatus(status: CardRequestStatus): CardRequest[] {
  return mockCardRequests.filter(req => req.status === status)
}

export function getFraudAlertsByLevel(level: FraudAlertLevel): FraudAlert[] {
  return mockFraudAlerts.filter(alert => alert.level === level)
}

export function getActiveSubscriptions(): Subscription[] {
  return mockSubscriptions.filter(sub => sub.status === 'ACTIVE')
}

export function getTotalMonthlySubscriptionCost(): number {
  return mockSubscriptions
    .filter(sub => sub.status === 'ACTIVE' && sub.billingFrequency === 'MONTHLY')
    .reduce((total, sub) => total + sub.amount, 0)
}

export function getCardsByDepartment(department: string): CorporateCard[] {
  return mockCorporateCards.filter(card => card.department === department)
}

export function getCardsByStatus(status: CardStatus): CorporateCard[] {
  return mockCorporateCards.filter(card => card.status === status)
}

export function getRecentTransactions(limit: number = 10): Transaction[] {
  return [...mockTransactions]
    .sort((a, b) => new Date(b.transactionDate).getTime() - new Date(a.transactionDate).getTime())
    .slice(0, limit)
}

export function getPendingTransactions(): Transaction[] {
  return mockTransactions.filter(txn => txn.status === 'PENDING')
}

export function getDisputedTransactions(): Transaction[] {
  return mockTransactions.filter(txn => txn.status === 'DISPUTED')
}

export function getUnreviewedFraudAlerts(): FraudAlert[] {
  return mockFraudAlerts.filter(alert => !alert.reviewed)
}
