import type { Event, TicketType, Attendee } from '@/types/events'

export const MOCK_EVENTS: Event[] = [
  {
    id: 'event-1',
    eventCode: 'EVT-2026-001',
    name: 'Tech Innovation Summit 2026',
    description: 'Annual technology conference featuring industry leaders, workshops, and networking opportunities.',
    category: 'conference',
    venue: 'Convention Center',
    address: '123 Tech Boulevard, San Francisco, CA 94102',
    startDateTime: '2026-03-15T09:00:00',
    endDateTime: '2026-03-17T18:00:00',
    status: 'published',
    capacity: 5000,
    ticketsSold: 3247,
    ticketsAvailable: 1753,
    totalRevenue: 649400,
    currency: 'USD',
    organizerName: 'TechEvents Inc',
    organizerEmail: 'events@techevents.com',
    createdAt: '2025-12-01T10:00:00',
  },
  {
    id: 'event-2',
    eventCode: 'EVT-2026-002',
    name: 'Summer Music Festival',
    description: 'Three-day outdoor music festival featuring top artists and bands across multiple stages.',
    category: 'concert',
    venue: 'Golden Gate Park',
    address: 'Golden Gate Park, San Francisco, CA 94118',
    startDateTime: '2026-07-10T14:00:00',
    endDateTime: '2026-07-12T23:00:00',
    status: 'published',
    capacity: 15000,
    ticketsSold: 12500,
    ticketsAvailable: 2500,
    totalRevenue: 1875000,
    currency: 'USD',
    organizerName: 'Live Music Productions',
    organizerEmail: 'info@livemusicpro.com',
    createdAt: '2025-11-15T14:30:00',
  },
  {
    id: 'event-3',
    eventCode: 'EVT-2026-003',
    name: 'Digital Marketing Masterclass',
    description: 'Intensive one-day workshop on modern digital marketing strategies and tools.',
    category: 'workshop',
    venue: 'Creative Hub',
    address: '456 Market Street, San Francisco, CA 94105',
    startDateTime: '2026-02-20T09:00:00',
    endDateTime: '2026-02-20T17:00:00',
    status: 'ongoing',
    capacity: 200,
    ticketsSold: 185,
    ticketsAvailable: 15,
    totalRevenue: 55500,
    currency: 'USD',
    organizerName: 'Marketing Academy',
    organizerEmail: 'workshops@marketingacademy.com',
    createdAt: '2025-12-10T09:00:00',
  },
  {
    id: 'event-4',
    eventCode: 'EVT-2026-004',
    name: 'Startup Networking Mixer',
    description: 'Monthly networking event for startup founders, investors, and entrepreneurs.',
    category: 'networking',
    venue: 'Innovation Lounge',
    address: '789 Startup Avenue, San Francisco, CA 94107',
    startDateTime: '2026-02-05T18:00:00',
    endDateTime: '2026-02-05T21:00:00',
    status: 'completed',
    capacity: 150,
    ticketsSold: 142,
    ticketsAvailable: 0,
    totalRevenue: 7100,
    currency: 'USD',
    organizerName: 'Startup Community SF',
    organizerEmail: 'events@startupsf.com',
    createdAt: '2026-01-05T12:00:00',
  },
  {
    id: 'event-5',
    eventCode: 'EVT-2026-005',
    name: 'Annual Charity Run 2026',
    description: '10K charity run supporting local education initiatives with prizes and refreshments.',
    category: 'sports',
    venue: 'City Park',
    address: 'Central Park, San Francisco, CA 94112',
    startDateTime: '2026-04-15T07:00:00',
    endDateTime: '2026-04-15T12:00:00',
    status: 'published',
    capacity: 1000,
    ticketsSold: 756,
    ticketsAvailable: 244,
    totalRevenue: 37800,
    currency: 'USD',
    organizerName: 'Community Sports Foundation',
    organizerEmail: 'charity@communitysports.org',
    createdAt: '2025-12-20T08:00:00',
  },
  {
    id: 'event-6',
    eventCode: 'EVT-2026-006',
    name: 'AI & Machine Learning Conference',
    description: 'Cutting-edge conference on artificial intelligence and machine learning applications.',
    category: 'conference',
    venue: 'Tech Campus',
    address: '321 Innovation Drive, San Francisco, CA 94103',
    startDateTime: '2026-05-20T09:00:00',
    endDateTime: '2026-05-22T17:00:00',
    status: 'draft',
    capacity: 2000,
    ticketsSold: 0,
    ticketsAvailable: 2000,
    totalRevenue: 0,
    currency: 'USD',
    organizerName: 'AI Research Institute',
    organizerEmail: 'conference@airesearch.org',
    createdAt: '2026-01-10T15:00:00',
  },
]

export const MOCK_TICKET_TYPES: TicketType[] = [
  // Tech Innovation Summit tickets
  {
    id: 'ticket-1',
    eventId: 'event-1',
    name: 'Early Bird',
    description: 'Limited early bird discount - Full 3-day access',
    price: 149,
    currency: 'USD',
    quantity: 500,
    quantitySold: 500,
    status: 'sold-out',
    benefits: ['All conference sessions', 'Networking events', 'Conference materials'],
    salesStart: '2025-12-01T00:00:00',
    salesEnd: '2026-01-15T23:59:59',
  },
  {
    id: 'ticket-2',
    eventId: 'event-1',
    name: 'General Admission',
    description: 'Standard 3-day conference pass',
    price: 249,
    currency: 'USD',
    quantity: 3000,
    quantitySold: 2247,
    status: 'available',
    benefits: ['All conference sessions', 'Networking events', 'Conference materials'],
    salesStart: '2026-01-16T00:00:00',
    salesEnd: '2026-03-14T23:59:59',
  },
  {
    id: 'ticket-3',
    eventId: 'event-1',
    name: 'VIP Pass',
    description: 'Premium experience with exclusive access',
    price: 499,
    currency: 'USD',
    quantity: 200,
    quantitySold: 150,
    status: 'available',
    benefits: ['All sessions', 'VIP lounge access', 'Speaker meet & greet', 'Premium seating'],
    salesStart: '2025-12-01T00:00:00',
    salesEnd: '2026-03-14T23:59:59',
  },
  // Summer Music Festival tickets
  {
    id: 'ticket-4',
    eventId: 'event-2',
    name: 'General Admission',
    description: '3-day festival pass',
    price: 150,
    currency: 'USD',
    quantity: 10000,
    quantitySold: 8500,
    status: 'available',
    benefits: ['Access to all stages', 'Festival wristband', 'Re-entry allowed'],
    salesStart: '2025-11-15T00:00:00',
    salesEnd: '2026-07-09T23:59:59',
  },
  {
    id: 'ticket-5',
    eventId: 'event-2',
    name: 'VIP Experience',
    description: 'Premium festival experience',
    price: 350,
    currency: 'USD',
    quantity: 1000,
    quantitySold: 950,
    status: 'available',
    benefits: ['VIP viewing areas', 'Exclusive lounge', 'Premium restrooms', 'Fast track entry'],
    salesStart: '2025-11-15T00:00:00',
    salesEnd: '2026-07-09T23:59:59',
  },
  // Digital Marketing Masterclass tickets
  {
    id: 'ticket-6',
    eventId: 'event-3',
    name: 'Standard Ticket',
    description: 'Full-day workshop access',
    price: 300,
    currency: 'USD',
    quantity: 200,
    quantitySold: 185,
    status: 'available',
    benefits: ['Workshop materials', 'Lunch included', 'Certificate of completion'],
    salesStart: '2025-12-10T00:00:00',
    salesEnd: '2026-02-19T23:59:59',
  },
]

export const MOCK_ATTENDEES: Attendee[] = [
  {
    id: 'attendee-1',
    ticketCode: 'TKT-2026-001234',
    eventId: 'event-1',
    ticketTypeId: 'ticket-2',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@example.com',
    phone: '+1 (555) 123-4567',
    ticketPrice: 249,
    purchaseDate: '2026-01-20T14:30:00',
    status: 'registered',
    checkedIn: false,
  },
  {
    id: 'attendee-2',
    ticketCode: 'TKT-2026-001235',
    eventId: 'event-1',
    ticketTypeId: 'ticket-3',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@example.com',
    phone: '+1 (555) 234-5678',
    ticketPrice: 499,
    purchaseDate: '2025-12-15T10:20:00',
    status: 'registered',
    checkedIn: false,
  },
  {
    id: 'attendee-3',
    ticketCode: 'TKT-2026-001236',
    eventId: 'event-1',
    ticketTypeId: 'ticket-2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'mchen@example.com',
    phone: '+1 (555) 345-6789',
    ticketPrice: 249,
    purchaseDate: '2026-02-01T09:15:00',
    status: 'registered',
    checkedIn: false,
  },
  {
    id: 'attendee-4',
    ticketCode: 'TKT-2026-001237',
    eventId: 'event-2',
    ticketTypeId: 'ticket-4',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    phone: '+1 (555) 456-7890',
    ticketPrice: 150,
    purchaseDate: '2025-12-20T16:45:00',
    status: 'registered',
    checkedIn: false,
  },
  {
    id: 'attendee-5',
    ticketCode: 'TKT-2026-001238',
    eventId: 'event-3',
    ticketTypeId: 'ticket-6',
    firstName: 'David',
    lastName: 'Wilson',
    email: 'david.w@example.com',
    phone: '+1 (555) 567-8901',
    ticketPrice: 300,
    purchaseDate: '2026-01-10T11:30:00',
    status: 'checked-in',
    checkedIn: true,
    checkInTime: '2026-02-20T08:45:00',
  },
]

// Helper function to get tickets for an event
export function getTicketsForEvent(eventId: string): TicketType[] {
  return MOCK_TICKET_TYPES.filter((ticket) => ticket.eventId === eventId)
}

// Helper function to get attendees for an event
export function getAttendeesForEvent(eventId: string): Attendee[] {
  return MOCK_ATTENDEES.filter((attendee) => attendee.eventId === eventId)
}

// Helper function to get attendees with ticket info
export function getPopulatedAttendees(eventId?: string): (Attendee & { ticketType?: TicketType; event?: Event })[] {
  const attendees = eventId ? getAttendeesForEvent(eventId) : MOCK_ATTENDEES

  return attendees.map((attendee) => ({
    ...attendee,
    ticketType: MOCK_TICKET_TYPES.find((t) => t.id === attendee.ticketTypeId),
    event: MOCK_EVENTS.find((e) => e.id === attendee.eventId),
  }))
}
